name: SlackMessage
on:
  status:

  workflow_dispatch:
  
jobs:
  if_error_or_failure:
    runs-on: ubuntu-latest
    if: >-
      github.event.state == 'error' ||
      github.event.state == 'failure'
    steps:
      - env:
          DESCRIPTION: ${{ github.event.description }}
        run: |
          echo The status is error or failed: $DESCRIPTION
      - name: Publish to slack channel via bot token
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: 'SLACK_CHANNEL_ID' # ID of Slack Channel you want to post to
          slack-message: 'posting from a github action!' # The message you want to post
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
